version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=simulide-local
      - POSTGRES_PASSWORD=simulide-pw
      - POSTGRES_DB=simulide-local
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - simulide-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: simulide-local
      POSTGRES_PASSWORD: simulide-pw
      POSTGRES_DB: simulide-local
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
    networks:
      - simulide-network

networks:
  simulide-network:
    driver: bridge
