name: CI Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build Docker Compose services
      - name: Build Docker Compose services
        run: docker-compose build

      # Step 3: Save Docker Compose build cache
      - name: Save Docker Compose build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose-artifacts
          path: .
          if-no-files-found: ignore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Restore Docker Compose artifacts
      - name: Download Docker Compose build artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-compose-artifacts

      # Step 3: Start Docker Compose services
      - name: Start Docker Compose services
        run: docker-compose up -d

      # Step 4: Run tests
      - name: Run tests using Gradle
        run: docker-compose exec app ./gradlew test

      # Step 5: Shut down services
      - name: Stop Docker Compose services
        run: docker-compose down
