name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Amazon Corretto 22
      - name: Set up Amazon Corretto 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t collaborative-editor .

      # Step 4: Save Docker image as artifact
      - name: Save Docker image as artifact
        run: |
          docker save collaborative-editor -o collaborative-editor.tar
        uses: actions/upload-artifact@v3
        with:
          name: collaborative-editor
          path: collaborative-editor.tar

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download Docker image artifact
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: collaborative-editor

      # Step 3: Load Docker image
      - name: Load Docker image
        run: docker load -i collaborative-editor.tar

      # Step 4: Run tests in Docker container
      - name: Run tests in Docker container
        run: docker run --rm collaborative-editor ./gradlew test
