name: CI Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 3: Build Docker Compose services
      - name: Build Docker Compose services
        run: docker-compose build

      # Step 4: Save Docker Compose build artifacts
      - name: Save Docker Compose build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose-artifacts
          path: .
          if-no-files-found: ignore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 3: Restore Docker Compose artifacts
      - name: Download Docker Compose build artifacts
        uses: actions/download-artifact@v3
        with:
          name: docker-compose-artifacts

      # Step 4: Start Docker Compose services
      - name: Start Docker Compose services
        run: docker-compose up -d

      # Step 5: Run tests
      - name: Run tests using Gradle
        run: docker-compose exec app ./gradlew test

      # Step 6: Shut down services
      - name: Stop Docker Compose services
        run: docker-compose down
