name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Amazon Corretto 22
      - name: Set up Amazon Corretto 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t collaborative-editor .

      # Step 4: Save Docker image as artifact
      - name: Save Docker image
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ./docker-image.tar
        run: |
          docker save collaborative-editor > docker-image.tar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Restore Docker image
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      # Step 3: Load Docker image
      - name: Load Docker image
        run: |
          docker load < docker-image.tar

      # Step 4: Run tests
      - name: Run tests in Docker container
        run: |
          docker run --rm collaborative-editor ./gradlew test
