name: CI Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker Compose services
        run: docker-compose build

      - name: Save Docker Compose build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose-artifacts
          path: .
          if-no-files-found: ignore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests using Gradle
        run: ./gradlew test
