name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Amazon Corretto 22
      - name: Set up Amazon Corretto 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t collaborative-editor .

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Amazon Corretto 22
      - name: Set up Amazon Corretto 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'

      # Step 3: Run tests in Docker container
      - name: Run tests in Docker container
        run: docker run --rm collaborative-editor ./gradlew test
